version: '3'
services:
  orca-proxy:
    build: ./orca_proxy
    ports:
      - "80:80"
  orca-ui:
    build: ..
    stdin_open: true
    network_mode: "service:orca-proxy"
    environment:
      - "REACT_APP_BACKEND_HOST=http://localhost/api"
  orca-mock:
    build: ./orca_mock
    network_mode: "service:orca-proxy"
